---
version: '3'
services:
  bionic:
    build: ./
    container_name: bionic
    image: naftulikay/bionic-vm:latest
    # systemd will not boot without privileged
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    stop_grace_period: 1s
